# Assignment

Import numpy as np

In [1]:
import numpy as np

Make a python list => \[1,2,3,4,5\]

Convert it into numpy array and print it

In [2]:
pylist = [1, 2, 3, 4, 5]
np_array = np.array(pylist)
np_array

array([1, 2, 3, 4, 5])

Make a python matrix (3 x 3) => \[[1,2,3],[4,5,6],[7,8,9]\]

Convert it into numpy array and print it

In [3]:
pymat = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
np_mat = np.array(pymat)
np_mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Make a matrix (3 x 3) using built-in methods (like arange(), reshape() etc.):

\[ [1,3,5],

 [7,9,11],
 
 [13,15,17] \]

In [9]:
matrix = np.arange(1, 18, 2)
print(matrix)
res_matrix = matrix.reshape((3, 3))
print(res_matrix)

[ 1  3  5  7  9 11 13 15 17]
[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]


Create a numpy array with 10 random numbers from 0 to 10 (there should be few numbers greater than 1)

In [16]:
array = np.random.randint(0, 11, 10)
array

array([10,  9,  6,  9,  1,  4, 10,  4,  2,  4])

Create numpy array => \[1,2,3,4,5\] and convert it to 2D array with 5 rows

In [23]:
array = np.array([1, 2, 3, 4, 5])
narray = array.reshape((5,1))
narray

array([[1],
       [2],
       [3],
       [4],
       [5]])

Print the shape of the above created array

In [24]:
narray.shape

(5, 1)

Create a numpy array with 10 elements in it. Access and print its 3rd, 4th and 9th element.

In [25]:
array = np.random.randint(0, 11, 10)
print(array)
print(array[2])
print(array[3])
print(array[8])

[ 6  7  2  1  8  7 10  0  9  1]
2
1
9


Print alternate elements of that array

In [26]:
for i in range(len(array)):
  if i % 2 == 0:
    print(array[i])

6
2
8
10
9


Change last 3 elements into 100 using broadcasting and print

In [27]:
array[-3 :] = 100
array

array([  6,   7,   2,   1,   8,   7,  10, 100, 100, 100])

Create a 5 x 5 matrix (fill it with any element you like), print it.

Then print the middle (3 x 3) matrix.

In [33]:
array = np.random.randint(0, 50, (5, 5))
print(array)
print("____________________________________________________")
array[1:4, 1:4]

[[26 21 21 15 29]
 [43 14 35  4 16]
 [16 39 23 10 25]
 [40 30 18 37 17]
 [45 12 26 30 39]]
____________________________________________________


array([[14, 35,  4],
       [39, 23, 10],
       [30, 18, 37]])